//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trecere
    {
        public int Id { get; set; }
        public Nullable<int> NrPunct { get; set; }
        public Nullable<int> IdCopil { get; set; }
        public Nullable<System.DateTime> DataTrecere { get; set; }
    
        public virtual Copil Copil { get; set; }
        public virtual Punct Punct { get; set; }
    }
}
