//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Joc()
        {
            this.Mutares = new HashSet<Mutare>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdJucator1 { get; set; }
        public Nullable<int> IdJucator2 { get; set; }
        public Nullable<int> PozitieJucator1 { get; set; }
        public Nullable<int> PozitieJucator2 { get; set; }
    
        public virtual Jucator Jucator { get; set; }
        public virtual Jucator Jucator1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mutare> Mutares { get; set; }
    }
}
