//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participare
    {
        public int Id { get; set; }
        public Nullable<int> IdJucator { get; set; }
        public Nullable<int> IdJoc { get; set; }
    
        public virtual Joc Joc { get; set; }
        public virtual Jucator Jucator { get; set; }
    }
}
